<?php

namespace Brains\PlatformBundle\Repository;

/**
 * Cours_PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cours_PartieRepository extends \Doctrine\ORM\EntityRepository
{
}
