<?php

namespace Brains\PlatformBundle\Repository;

/**
 * Cours_QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cours_QuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
