<?php

namespace Brains\PlatformBundle\Repository;

/**
 * Exo_QuestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exo_QuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
