<?php

namespace Brains\PlatformBundle\Repository;

/**
 * Exo_PartieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Exo_PartieRepository extends \Doctrine\ORM\EntityRepository
{
}
