<?php

namespace Brains\PlatformBundle\Repository;

/**
 * exo_viewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class exo_viewsRepository extends \Doctrine\ORM\EntityRepository
{
}
