<?php

namespace Brains\PlatformBundle\Repository;

/**
 * SoufianeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoufianeRepository extends \Doctrine\ORM\EntityRepository
{
}
