brains_platform_homepage:
    path:     /home
    defaults: { _controller: BrainsPlatformBundle:Default:index }
brains_platform_mail:
    path:     /mail
    defaults: { _controller: BrainsPlatformBundle:Default:send_mail }
brains_platform_role:
    path:     /role
    defaults: { _controller: BrainsPlatformBundle:Default:test_role }
brains_platform_n_annee:
    path:     /n_annee
    defaults: { _controller: BrainsPlatformBundle:Creation:n_annee }
brains_platform_n_filiere:
    path:     /n_filiere
    defaults: { _controller: BrainsPlatformBundle:Filiere:n_filiere }
BP_show_filiere:
    path:     /show_filiere
    defaults: { _controller: BrainsPlatformBundle:Filiere:show_filiere }
BP_update_filiere:
    path:     /show_filiere/{id}
    defaults: { _controller: BrainsPlatformBundle:Filiere:update_filiere }
BP_delete_filiere:
    path:     /delete_filiere/{id}
    defaults: { _controller: BrainsPlatformBundle:Filiere:delete_filiere }