brains_platform_homepage:
    path:     /
    defaults: { _controller: BrainsPlatformBundle:Default:index }
brains_platform_mail:
    path:     /mail
    defaults: { _controller: BrainsPlatformBundle:Default:send_mail }
brains_platform_role:
    path:     /role
    defaults: { _controller: BrainsPlatformBundle:Default:test_role }
brains_platform_n_annee:
    path:     /n_annee
    defaults: { _controller: BrainsPlatformBundle:Creation:n_annee }
brains_platform_n_filiere:
    path:     /n_filiere
    defaults: { _controller: BrainsPlatformBundle:Creation:n_filiere }