brains_platform_homepage:
    path:     /
    defaults: { _controller: BrainsPlatformBundle:Default:index }
brains_platform_mail:
    path:     /mail
    defaults: { _controller: BrainsPlatformBundle:Default:send_mail }
