brains_user_profile:
    path:     /user
    defaults: { _controller: BrainsUserBundle:Security:profile }
brains_user_update:
    path:     /update_user
    defaults: { _controller: BrainsUserBundle:Security:update_user }
brains_user_homepage:
    path:     /users
    defaults: { _controller: BrainsUserBundle:UserManagement:getUsers }
